export const APP_NAME =
  'SISTEM INFORMASI PENYEWAAN PERLENGKAPAN PERNIKAHAN DI NELLYSALON WAINGAPU BERBASIS WEB PADA DINAS KESEHATAN KABUPATEN SUMBA TIMUR';
export const BASE_URL = '';
export const ROUNDED_SALT_BCRYPT = 11;
export const PORT = "8081"